[package]
name = "micox"
version = "0.0.0"
edition = "2018"
authors = ["airt <airtial@gmail.com>"]

[dependencies]
bootloader = "0.6"
volatile = "0.2"
spin = "0.5"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]
