name: build

on:
  pull_request:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: clippy, rustfmt, rust-src, llvm-tools-preview
      - run: sudo apt update
      - run: sudo apt install qemu-system-x86
      - run: cargo install cargo-xbuild
      - run: cargo install bootimage
      - run: cargo fmt -- --check
      - run: cargo xclippy
      - run: cargo xtest
      - run: cargo xbuild
      - run: cargo bootimage
